//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Namu.Entity.DB;

namespace Namu.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbnamutestEntities : DbContext
    {
        public dbnamutestEntities()
            : base("name=dbnamutestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<taddress> taddresses { get; set; }
        public virtual DbSet<tprovider> tproviders { get; set; }
        public virtual DbSet<tprovider_hoteltype> tprovider_hoteltype { get; set; }
        public virtual DbSet<tprovider_tourtype> tprovider_tourtype { get; set; }
        public virtual DbSet<troomcategory> troomcategories { get; set; }
        public virtual DbSet<ttoken> ttokens { get; set; }
        public virtual DbSet<ttour> ttours { get; set; }
        public virtual DbSet<tuser> tusers { get; set; }
    }
}
