//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Namu.Entity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tprovider_hoteltype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tprovider_hoteltype()
        {
            this.troomcategories = new HashSet<troomcategory>();
        }
    
        public int idtprovider { get; set; }
        public int checkin_hour { get; set; }
        public int checkin_minute { get; set; }
        public int checkout_hour { get; set; }
        public int checkout_minute { get; set; }
        public int minimum_age { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual tprovider tprovider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<troomcategory> troomcategories { get; set; }
    }
}
