//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Namu.Entity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class troomcategory
    {
        public int idtroomcategory { get; set; }
        public string name { get; set; }
        public int maxcapacity { get; set; }
        public int fktprovider { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual tprovider_hoteltype tprovider_hoteltype { get; set; }
    }
}
