//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Namu.Entity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ttoken
    {
        public int idttokens { get; set; }
        public string authToken { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int fktuser { get; set; }
    
        public virtual tuser tuser { get; set; }
    }
}
