//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Namu.Entity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tuser()
        {
            this.ttokens = new HashSet<ttoken>();
        }
    
        public int idtuser { get; set; }
        public string name { get; set; }
        public string passwordCypher { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ttoken> ttokens { get; set; }
    }
}
